# Generated by Django 6.0.7 on 2026-08-04 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedLoadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('planned_duration_minutes', models.FloatField()),
                ('planned_tps', models.FloatField()),
                ('jmeter_csv_filename', models.CharField(blank=True, default='', max_length=255)),
                ('server_metrics_csv_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('recorded', 'Recorded')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='load_test_tracker.loadtestplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LoadTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeter_csv_filename', models.CharField(max_length=255)),
                ('server_metrics_csv_filename', models.CharField(max_length=255)),
                ('sample_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_rate_percent', models.FloatField(blank=True, null=True)),
                ('actual_duration_seconds', models.FloatField(blank=True, null=True)),
                ('actual_tps', models.FloatField(blank=True, null=True)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('min_response_time_ms', models.FloatField(blank=True, null=True)),
                ('max_response_time_ms', models.FloatField(blank=True, null=True)),
                ('p50_response_time_ms', models.FloatField(blank=True, null=True)),
                ('p90_response_time_ms', models.FloatField(blank=True, null=True)),
                ('p95_response_time_ms', models.FloatField(blank=True, null=True)),
                ('p99_response_time_ms', models.FloatField(blank=True, null=True)),
                ('response_time_series', models.JSONField(default=list)),
                ('throughput_series', models.JSONField(default=list)),
                ('cpu_ram_series', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planned_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='load_test_tracker.plannedloadtest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='plannedloadtest',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='unique_plan_test_order'),
        ),
    ]
