# Generated by Django 6.0.7 on 2026-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("load_test_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadtestresult",
            name="server_metrics_csv_filename",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
