# Generated by Django 6.0.7 on 2026-08-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogViewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs_dir', models.CharField(max_length=1000)),
                ('log4j_xml_path', models.CharField(blank=True, default='', max_length=1000)),
                ('pattern_source', models.CharField(blank=True, choices=[('log4j_xml', 'log4j XML'), ('default', 'Default (Spring Boot)')], default='', max_length=20)),
                ('conversion_pattern', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_count', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
                ('warnings', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('source_file', models.CharField(max_length=255)),
                ('line_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('level', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('thread', models.CharField(blank=True, default='', max_length=255)),
                ('logger', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('is_request_like', models.BooleanField(default=False)),
                ('is_response_like', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='log_viewer.logviewjob')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
    ]
