# Generated by Django 6.0.7 on 2026-07-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_curl', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('body', models.JSONField(blank=True, null=True)),
                ('body_raw', models.TextField(blank=True, null=True)),
                ('is_json_body', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='apitester.importedrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.TextField()),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('request_body_raw', models.TextField(blank=True, null=True)),
                ('body_mode', models.CharField(default='none', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('handled', 'Handled'), ('review', 'Review'), ('error', 'Error'), ('info', 'Info')], max_length=20, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='apitester.testrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
