# Generated by Django 6.0.7 on 2026-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='body_field_tests',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='testrun',
            name='header_tests',
            field=models.JSONField(default=dict),
        ),
    ]
