# Generated by Django 6.0.7 on 2026-07-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitester', '0002_testrun_body_field_tests_testrun_header_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='rate_limit_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='rate_limit_wait_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outcome',
            field=models.CharField(blank=True, choices=[('handled', 'Handled'), ('review', 'Review'), ('error', 'Error'), ('info', 'Info'), ('rate_limited', 'Rate limited')], max_length=20, null=True),
        ),
    ]
