# Generated by Django 6.0.7 on 2026-07-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitester', '0003_testcase_rate_limit_retries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
