# Generated by Django 6.0.7 on 2026-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitester', '0004_testrun_verify_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
