# Generated by Django 6.0.7 on 2026-08-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitester', '0005_testrun_stop_requested_alter_testrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='human_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
