# Generated by Django 6.0.7 on 2026-08-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_curl', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('body', models.JSONField(blank=True, null=True)),
                ('body_raw', models.TextField(blank=True, null=True)),
                ('is_json_body', models.BooleanField(default=False)),
                ('credential_fields', models.JSONField(default=list)),
                ('current_values', models.JSONField(default=dict)),
                ('expiration_status_code', models.IntegerField(blank=True, null=True)),
                ('expiration_message_contains', models.CharField(blank=True, default='', max_length=500)),
                ('categories', models.JSONField(default=list)),
                ('body_field_tests', models.JSONField(default=dict)),
                ('header_tests', models.JSONField(default=dict)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused_awaiting_credentials', 'Paused (awaiting fresh credentials)'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('pause_count', models.IntegerField(default=0)),
                ('pause_reason', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.TextField()),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('request_body_raw', models.TextField(blank=True, null=True)),
                ('body_mode', models.CharField(default='none', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('handled', 'Handled'), ('review', 'Review'), ('error', 'Error'), ('info', 'Info'), ('rate_limited', 'Rate limited')], max_length=20, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_retries', models.IntegerField(default=0)),
                ('rate_limit_wait_seconds', models.FloatField(default=0)),
                ('credential_values_used', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='credential_tester.credentialrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
