# Generated by Django 6.0.7 on 2026-07-27 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(default=list)),
                ('body_field_tests', models.JSONField(default=dict)),
                ('header_tests', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='chain_tester.apichain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('raw_curl', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('body', models.JSONField(blank=True, null=True)),
                ('body_raw', models.TextField(blank=True, null=True)),
                ('is_json_body', models.BooleanField(default=False)),
                ('refresh_mode', models.CharField(choices=[('once', 'Once'), ('per_test', 'Per test')], default='once', max_length=10)),
                ('extract_rules', models.JSONField(default=dict)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='chain_tester.apichain')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChainStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('extracted', models.JSONField(default=dict)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('chain_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='chain_tester.chainrun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain_tester.chainstep')),
            ],
            options={
                'ordering': ['step__order'],
            },
        ),
        migrations.CreateModel(
            name='ChainTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('request_url', models.TextField()),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('request_body_raw', models.TextField(blank=True, null=True)),
                ('body_mode', models.CharField(default='none', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('handled', 'Handled'), ('review', 'Review'), ('error', 'Error'), ('info', 'Info'), ('rate_limited', 'Rate limited')], max_length=20, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_retries', models.IntegerField(default=0)),
                ('rate_limit_wait_seconds', models.FloatField(default=0)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('chain_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='chain_tester.chainrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='chainstep',
            constraint=models.UniqueConstraint(fields=('chain', 'order'), name='unique_chain_step_order'),
        ),
    ]
