# Generated by Django 6.0.7 on 2026-07-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainrun',
            name='verify_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
