# Generated by Django 6.0.7 on 2026-08-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('environment', models.CharField(blank=True, default='', max_length=255)),
                ('pre_requisite', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('sprint', models.CharField(blank=True, default='', max_length=255)),
                ('lob', models.CharField(blank=True, default='', max_length=255)),
                ('vertical', models.CharField(blank=True, default='', max_length=255)),
                ('feasible_for_automation', models.CharField(blank=True, default='', max_length=255)),
                ('test_case_applicability', models.CharField(blank=True, default='', max_length=255)),
                ('labels', models.CharField(blank=True, default='', max_length=255)),
                ('test_case_status', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='manual_test_cases.manualtestsuite')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ManualTestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('test_data', models.TextField(blank=True, default='')),
                ('expected_result', models.TextField(blank=True, default='')),
                ('actual_result', models.TextField(blank=True, default='')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='manual_test_cases.manualtestcase')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('test_case', 'order'), name='unique_case_step_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='manualtestcase',
            constraint=models.UniqueConstraint(fields=('suite', 'order'), name='unique_suite_case_order'),
        ),
    ]
