# Generated by Django 6.0.7 on 2026-07-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KarateTestCaseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_dir', models.CharField(max_length=1000)),
                ('excel_path', models.CharField(max_length=1000)),
                ('environment', models.CharField(blank=True, default='', max_length=255)),
                ('pre_requisite', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('sprint', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('feature_count', models.IntegerField(default=0)),
                ('scenario_count', models.IntegerField(default=0)),
                ('step_count', models.IntegerField(default=0)),
                ('warnings', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
