# Generated by Django 6.0.7 on 2026-07-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karate_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karatetestcasejob',
            name='feasible_for_automation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='karatetestcasejob',
            name='labels',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='karatetestcasejob',
            name='lob',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='karatetestcasejob',
            name='test_case_applicability',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='karatetestcasejob',
            name='test_case_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='karatetestcasejob',
            name='vertical',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
